# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/Computer_Organization_Project/project_cpu/project_cpu.runs/synth_1/.Xil/Vivado-15568-LAPTOP-END1HUJS/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    e:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/ip/clk_wiz_0
    e:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/ip/inst_memory
  } {
      E:/Digital_logic/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      E:/Digital_logic/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    e:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/ip/clk_wiz_0
    e:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/ip/inst_memory
  } {
      E:/Computer_Organization_Project/project_cpu/project_cpu.runs/synth_1/.Xil/Vivado-15568-LAPTOP-END1HUJS/realtime/inst_memory_stub.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.runs/synth_1/.Xil/Vivado-15568-LAPTOP-END1HUJS/realtime/data_memory_stub.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.runs/synth_1/.Xil/Vivado-15568-LAPTOP-END1HUJS/realtime/clk_wiz_0_stub.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/new/ALU.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/new/Decoder.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/new/IFetch.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/new/MemOrIO.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/new/clock_div.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/new/control.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/new/debouncer.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/new/led.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/new/m_data.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/new/seg.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/new/switch.v
      E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/new/top.v
    }
      rt::read_vhdl -lib xpm E:/Digital_logic/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList E:/Computer_Organization_Project/project_cpu/project_cpu.runs/synth_1/.Xil/Vivado-15568-LAPTOP-END1HUJS/realtime/top_synth.xdc
    rt::sdcChecksum
    set rt::top top
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {E:/Computer_Organization_Project/project_cpu/project_cpu.cache/wt}
    rt::set_parameter enableSplitFlowPath "E:/Computer_Organization_Project/project_cpu/project_cpu.runs/synth_1/.Xil/Vivado-15568-LAPTOP-END1HUJS/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
