set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports clkIn]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports rst]

set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVCMOS33} [get_ports switchLeft[0]]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD LVCMOS33} [get_ports switchLeft[1]]
set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports switchLeft[2]]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports switchLeft[3]]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD LVCMOS33} [get_ports switchLeft[4]]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports switchLeft[5]]
set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33} [get_ports switchLeft[6]]
set_property -dict {PACKAGE_PIN P5 IOSTANDARD LVCMOS33} [get_ports switchLeft[7]]

set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVCMOS33} [get_ports switchRight[0]]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports switchRight[1]]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports switchRight[2]]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS33} [get_ports switchRight[3]]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33} [get_ports switchRight[4]]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS33} [get_ports switchRight[5]]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports switchRight[6]]
set_property -dict {PACKAGE_PIN U3 IOSTANDARD LVCMOS33} [get_ports switchRight[7]]

set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports button[0]]
set_property -dict {PACKAGE_PIN R11 IOSTANDARD LVCMOS33} [get_ports button[1]]
set_property -dict {PACKAGE_PIN V1  IOSTANDARD LVCMOS33} [get_ports button[2]]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports button[3]]
set_property -dict {PACKAGE_PIN U4  IOSTANDARD LVCMOS33} [get_ports button[4]]

set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports ledLeft[0]]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports ledLeft[1]]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports ledLeft[2]]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports ledLeft[3]]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports ledLeft[4]]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS33} [get_ports ledLeft[5]]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports ledLeft[6]]
set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVCMOS33} [get_ports ledLeft[7]]

set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports ledRight[0]]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports ledRight[1]]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports ledRight[2]]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS33} [get_ports ledRight[3]]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports ledRight[4]]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports ledRight[5]]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports ledRight[6]]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports ledRight[7]]

set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [get_ports {chipSel[0]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD LVCMOS33} [get_ports {chipSel[1]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS33} [get_ports {chipSel[2]}]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {chipSel[3]}]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports {chipSel[4]}]
set_property -dict {PACKAGE_PIN C1 IOSTANDARD LVCMOS33} [get_ports {chipSel[5]}]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports {chipSel[6]}]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports {chipSel[7]}]

set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports {segCtrl[0]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports {segCtrl[1]}]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports {segCtrl[2]}]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS33} [get_ports {segCtrl[3]}]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports {segCtrl[4]}]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {segCtrl[5]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {segCtrl[6]}]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {segCtrl[7]}]

set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports {segCtrr[0]}]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS33} [get_ports {segCtrr[1]}]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS33} [get_ports {segCtrr[2]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {segCtrr[3]}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports {segCtrr[4]}]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports {segCtrr[5]}]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports {segCtrr[6]}]
set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports {segCtrr[7]}]