# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/ip/inst_memory/inst_memory.xci
# IP: The module: 'inst_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/ip/inst_memory/inst_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/ip/inst_memory/inst_memory.xci
# IP: The module: 'inst_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Computer_Organization_Project/project_cpu/project_cpu.srcs/sources_1/ip/inst_memory/inst_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
