# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# IP: ip/clock_cpu/clock_cpu.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_cpu || ORIG_REF_NAME==clock_cpu} -quiet] -quiet
